<?php
/**
* @package      ClickedMe
* @version      $Id$
* @author       Florian Schießl
* @link         http://www.ifs-net.de
* @copyright    Copyright (C) 2008
* @license      http://www.gnu.org/copyleft/gpl.html GNU General Public License
*/

/**
 * the main user function
 */
function ClickedMe_user_main()
{
    // Security check
    if (!SecurityUtil::checkPermission('ClickedMe::', '::', ACCESS_COMMENT)) return Logutil::registerPermissionError();

    $dom = ZLanguage::getModuleDomain('ClickedMe');
		
    $action=FormUtil::getPassedValue('action');
    if (isset($action) && ($action=='update')) {
	// Is there a valid auth-key?
	if (SecurityUtil::confirmAuthKey()) {
	    pnModAPIFunc('ClickedMe','user','storeSettings');
	    LogUtil::registerStatus(__('Settings stored',$dom));
	}
        else LogUtil::registerAuthidError();
    }
				
    // Create output
    $pnRender = pnRender::getInstance('ClickedMe');
    
    // Assign data
    $uid = pnUserGetVar('uid');
    $pnRender->assign('uid', $uid);
    $pnRender->assign('privacy', pnModAPIFunc('ClickedMe','user','getSettings',array('uid' => $uid)));
		    
    // Return the output that has been generated by this function
    return $pnRender->fetch('clickedme_user_main.htm');
}

/**
 * the history display
 */
function ClickedMe_user_history()
{
    // Security check
    if (!SecurityUtil::checkPermission('ClickedMe::', '::', ACCESS_COMMENT)) return Logutil::registerPermissionError();
		
    // Create output
    $render = pnRender::getInstance('ClickedMe');
    
    // Assign data
    $uid = pnUserGetVar('uid');
    $render->assign(array(
    		'uid'		=> $uid,
    		'visitors'	=> pnModAPIFunc('ClickedMe','user','getViewers',array(
    						'uid'		=> $uid,
    						'amount'	=> 5
								)),
    		'history'	=> pnModAPIFunc('ClickedMe','user','getHistory',array(
    						'uid'		=> $uid,
    						'amount'	=> 5
								))
		));
		    
    // Return the output that has been generated by this function
    return $render->fetch('clickedme_user_history.htm');
}