<?php
/**
 * the main user function
 */
function ClickedMe_user_main()
{
    // Security check
    if (!SecurityUtil::checkPermission('ClickedMe::', '::', ACCESS_COMMENT)) return Logutil::registerPermissionError();
		
    $action=FormUtil::getPassedValue('action');
    if (isset($action) && ($action=='update')) {
	// Is there a valid auth-key?
	if (SecurityUtil::confirmAuthKey()) {
	    pnModAPIFunc('ClickedMe','user','storeSettings');
	    LogUtil::registerStatus(_PNCLICKEDMESTORED);
	}
        else LogUtil::registerAuthidError();
    }
				
    // Create output
    $pnRender =& new pnRender('ClickedMe');
		    
    // Return the output that has been generated by this function
    return $pnRender->fetch('clickedme_user_main.htm');
}

/**
 * the history display
 */
function ClickedMe_user_history()
{
    // Security check
    if (!SecurityUtil::checkPermission('ClickedMe::', '::', ACCESS_COMMENT)) return Logutil::registerPermissionError();
		
    // Create output
    $pnRender =& new pnRender('ClickedMe');
		    
    // Return the output that has been generated by this function
    return $pnRender->fetch('clickedme_user_history.htm');
}
?>
