<?php
/**
 * the main user function
 */
function ClickedMe_user_main()
{
    // Security check
    if (!pnSecAuthAction(0, 'ClickedMe::', '::', ACCESS_COMMENT)) {
        return pnVarPrepHTMLDisplay(_MODULENOAUTH);
    }
		
    $action=pnVarCleanFromInput('action');
    if (isset($action) && ($action=='update')) {
	// Is there a valid auth-key?
	if (pnSecConfirmAuthKey()) {
	    pnModAPIFunc('ClickedMe','user','storeSettings');
	    pnSessionSetVar('statusmsg',_PNCLICKEDMESTORED);
	}
        else pnSessionSetVar('errormsg',_PNCLICEKDMENOAUTHKEY);
    }
				
    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $pnRender =& new pnRender('ClickedMe');
		    
    // Return the output that has been generated by this function
    return $pnRender->fetch('clickedme_user_main.htm');
}

/**
 * the history display
 */
function ClickedMe_user_history()
{
    // Security check
    if (!pnSecAuthAction(0, 'ClickedMe::', '::', ACCESS_COMMENT)) {
        return pnVarPrepHTMLDisplay(_MODULENOAUTH);
    }
		
    // Create output object - this object will store all of our output so that
    // we can return it easily when required
    $pnRender =& new pnRender('ClickedMe');
		    
    // Return the output that has been generated by this function
    return $pnRender->fetch('clickedme_user_history.htm');
}
?>
