<?php

/**
 * initialise block
 * 
 * @author       The PostNuke Development Team
 */
function ClickedMe_lastblock_init()
{
    // nothing...
}

/**
 * get information on block
 * 
 * @author       The PostNuke Development Team
 * @return       array       The block information
 */
function ClickedMe_lastblock_info()
{
    return array('text_type'      => 'Last',
                 'module'         => 'ClickedMe',
                 'text_type_long' => 'Show usernames that clicked my profile (chronilogical)',
                 'allow_multiple' => true,
                 'form_content'   => false,
                 'form_refresh'   => false,
                 'show_preview'   => true);
}

/**
 * display block
 * 
 * @return       output      the rendered bock
 */
function ClickedMe_lastblock_display($blockinfo)
{

//    return pnModAPIFunc('ClickedMe','user','displaylast',array($blockinfo));

//we can remove this later..
    // Security check
    if (!pnSecAuthAction(0, 'ClickedMe:last:', "::", ACCESS_READ))	return;

    // this block is totally unusable for all unregistered users...
    if (!pnUserLoggedIn()) return;
    
    // Get variables from content block
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['numitems'])) {
        $vars['numitems'] = 15;
    }

    // Check if the ClickedMe module is available. 
    if (!pnModAvailable('ClickedMe')) {
	return false;
    }

    // Database information
    pnModDBInfoLoad('ClickedMe');
    $dbconn =& pnDBGetConn(true);
    $pntable =pnDBGetTables();
    $table = $pntable['clickedme'];
    $column = &$pntable['clickedme_column'];

    // Get the data from the database
    $sql = "SELECT $column[uid]
            FROM $table
	    WHERE $column[clicked_uid] = ".(int)pnUserGetVar('uid')."
	      AND $column[uid] != ".(int)pnUserGetVar('uid')."
            ORDER by $column[timestamp] DESC
	    ";
    $result = $dbconn->SelectLimit($sql, $vars['numitems']);
    if ($dbconn->ErrorNo() != 0) {
        return;
    }
    // if there is nothing return!
    if (!($result->RowCount()==0)) {
        $items=array();
	for (; !$result->EOF; $result->MoveNext()) {
	    unset($item);
	    list($item[uid])=$result->fields;
	    $item[uname]=pnUsergetVar('uname',$item[uid]);
	    $items[]=$item;
	}
    }
    // Create output object
    // Note that for a block the corresponding module must be passed.
    $pnRender =& new pnRender('ClickedMe');
	
    // Assign the items
    $pnRender->assign('items', $items);
	
    // Populate block info and pass to theme
    $blockinfo['content'] = $pnRender->fetch('clickedme_block_last.htm');

    return themesideblock($blockinfo);
}



/**
 * modify block settings
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the bock form
 */
function ClickedMe_lastblock_modify($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['numitems'])) {
        $vars['numitems'] = 5;
    }

    // Create output object
	$pnRender =& new pnRender('ClickedMe');

	// As Admin output changes often, we do not want caching.
	$pnRender->caching = false;

    // assign the approriate values
	$pnRender->assign('numitems', $vars['numitems']);

    // Return the output that has been generated by this function
	return $pnRender->fetch('clickedme_block_last_modify.htm');
}

/**
 * update block settings
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function ClickedMe_lastblock_update($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);
	
    // alter the corresponding variable
    $vars['numitems'] = pnVarCleanFromInput('numitems');
	
    // write back the new contents
    $blockinfo['content'] = pnBlockVarsToContent($vars);

    // clear the block cache
    $pnRender =& new pnRender('ClickedMe');
    $pnRender->clear_cache('clickedme_block_last.htm');
	
    return $blockinfo;
}
?>