<?php
/**
* @package      ClickedMe
* @version      $Id$
* @author       Florian Schießl
* @link         http://www.ifs-net.de
* @copyright    Copyright (C) 2008
* @license      http://www.gnu.org/copyleft/gpl.html GNU General Public License
*/

/**
 * initialise block
 * 
 * @author       The PostNuke Development Team
 */
function ClickedMe_lastblock_init()
{
    // nothing...
}

/**
 * get information on block
 * 
 * @author       The PostNuke Development Team
 * @return       array       The block information
 */
function ClickedMe_lastblock_info()
{
    return array('text_type'      => 'Last',
                 'module'         => 'ClickedMe',
                 'text_type_long' => 'Show usernames that clicked my profile (chronilogical)',
                 'allow_multiple' => true,
                 'form_content'   => false,
                 'form_refresh'   => false,
                 'show_preview'   => true);
}

/**
 * display block
 * 
 * @return       output      the rendered bock
 */
function ClickedMe_lastblock_display($blockinfo)
{

    // Security check and no access for guests
    if (!SecurityUtil::checkPermission('ClickedMe:last:',"::", ACCESS_READ) || !pnUserLoggedIn() || !pnModAvailable('ClickedMe')) return;

    // Get variables from content block
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['numitems'])) $vars['numitems'] = 5;
    $amount = $vars['numitems'];

	// get render instance
	$render = pnRender::getInstance('ClickedMe');

    // Assign data
    $uid = pnUserGetVar('uid');
    $render->assign(array(
    		'uid'		=> $uid,
    		'visitors'	=> pnModAPIFunc('ClickedMe','user','getViewers',array(
    						'uid'		=> $uid,
    						'amount'	=> 5
								))
		));
		    
    // Populate block info and pass to theme
    $blockinfo['content'] = $render->fetch('clickedme_block_last.htm');
    return themesideblock($blockinfo);
}

/**
 * modify block settings
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the bock form
 */
function ClickedMe_lastblock_modify($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['numitems'])) $vars['numitems'] = 5;

    // Create output object
	$render = pnRender::getInstance('ClickedMe');

	// As Admin output changes often, we do not want caching.
	$render->caching = false;

    // assign the approriate values
	$render->assign('numitems', $vars['numitems']);

    // Return the output that has been generated by this function
	return $render->fetch('clickedme_block_last_modify.htm');
}

/**
 * update block settings
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function ClickedMe_lastblock_update($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);
	
    // alter the corresponding variable
    $vars['numitems'] = pnVarCleanFromInput('numitems');
	
    // write back the new contents
    $blockinfo['content'] = pnBlockVarsToContent($vars);

    // clear the block cache
    $render = pnRender::getInstance('ClickedMe');
    $render->clear_cache('clickedme_block_last.htm');
    return $blockinfo;
}
?>